### ISSUE TITLE
No module named __init__

### ISSUE THREAD

**Issue by ilo-3a29** [velolala/touchosc2midi#13]
when I try to run touchosc2midi, I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/touchosc2midi", line 11, in <module>
    load_entry_point('touchosc2midi==0.0.9', 'console_scripts', 'touchosc2midi')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/touchosc2midi/touchosc2midi.py", line 19, in <module>
    from __init__ import __version__
ModuleNotFoundError: No module named '__init__'
```
any help?

**Comment by velolala** [comment]
oops, didn't mean to close. Let me try with python3.6 what the issue may be.
